FROM python:3.9

WORKDIR /app

# Install MySQL client tools
RUN apt-get update && apt-get install -y default-mysql-client && apt-get clean

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy initialization scripts
COPY init_db.sh .
RUN chmod +x init_db.sh

# Run init script
CMD ["./init_db.sh"]