version: '3.8'

services:
  student_app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/  # Mount the entire codebase to the root (/) of the container
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: student_welfare
      MYSQL_ROOT_PASSWORD: Domaaru07,
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
